// 60 монстрів бестіарію. XP і CR — за офіційною таблицею D&D 5e.
export const CATEGORIES = [
  { key: "water",    name: "Водяні та болотні" },
  { key: "forest",   name: "Лісові" },
  { key: "mountain", name: "Гірські" },
  { key: "fire",     name: "Вогняні" },
  { key: "undead",   name: "Нежить" },
  { key: "human",    name: "Люди / універсальні" },
];

export const BESTIARY = [
  {
    "id": 1,
    "name": "Глибинник",
    "type": "humanoid",
    "typeUk": "Гуманоїд",
    "cat": "water",
    "cr": "1/4",
    "xp": 50,
    "ac": 13,
    "hp": 18,
    "size": "Medium"
  },
  {
    "id": 2,
    "name": "Рифник",
    "type": "humanoid",
    "typeUk": "Гуманоїд",
    "cat": "water",
    "cr": "1/2",
    "xp": 100,
    "ac": 14,
    "hp": 22,
    "size": "Medium"
  },
  {
    "id": 3,
    "name": "Шипозуб",
    "type": "beast",
    "typeUk": "Звір",
    "cat": "water",
    "cr": "1/2",
    "xp": 100,
    "ac": 14,
    "hp": 30,
    "size": "Medium"
  },
  {
    "id": 4,
    "name": "Морський потворник",
    "type": "beast",
    "typeUk": "Звір",
    "cat": "water",
    "cr": "1",
    "xp": 200,
    "ac": 15,
    "hp": 45,
    "size": "Large"
  },
  {
    "id": 5,
    "name": "Водяний елементаль",
    "type": "elemental",
    "typeUk": "Елементаль",
    "cat": "water",
    "cr": "2",
    "xp": 450,
    "ac": 14,
    "hp": 75,
    "size": "Large"
  },
  {
    "id": 6,
    "name": "Гігантський крокодил",
    "type": "beast",
    "typeUk": "Звір",
    "cat": "water",
    "cr": "3",
    "xp": 700,
    "ac": 14,
    "hp": 85,
    "size": "Huge"
  },
  {
    "id": 7,
    "name": "Гігантська акула",
    "type": "beast",
    "typeUk": "Звір",
    "cat": "water",
    "cr": "5",
    "xp": 1800,
    "ac": 13,
    "hp": 110,
    "size": "Huge"
  },
  {
    "id": 8,
    "name": "Глибоководний мисливець",
    "type": "humanoid",
    "typeUk": "Гуманоїд",
    "cat": "water",
    "cr": "2",
    "xp": 450,
    "ac": 16,
    "hp": 55,
    "size": "Medium"
  },
  {
    "id": 9,
    "name": "Панцирник",
    "type": "beast",
    "typeUk": "Амфібія",
    "cat": "water",
    "cr": "3",
    "xp": 700,
    "ac": 17,
    "hp": 90,
    "size": "Large"
  },
  {
    "id": 10,
    "name": "Древній безодник",
    "type": "aberration",
    "typeUk": "Аберація",
    "cat": "water",
    "cr": "7",
    "xp": 2900,
    "ac": 18,
    "hp": 180,
    "size": "Huge"
  },
  {
    "id": 11,
    "name": "Лісовий гоблін",
    "type": "humanoid",
    "typeUk": "Гуманоїд",
    "cat": "forest",
    "cr": "1/8",
    "xp": 25,
    "ac": 15,
    "hp": 7,
    "size": "Small"
  },
  {
    "id": 12,
    "name": "Зелений рейдер",
    "type": "humanoid",
    "typeUk": "Гуманоїд",
    "cat": "forest",
    "cr": "1/2",
    "xp": 100,
    "ac": 16,
    "hp": 18,
    "size": "Medium"
  },
  {
    "id": 13,
    "name": "Кривозуб",
    "type": "beast",
    "typeUk": "Звір",
    "cat": "forest",
    "cr": "1/2",
    "xp": 100,
    "ac": 13,
    "hp": 27,
    "size": "Medium"
  },
  {
    "id": 14,
    "name": "Колючник",
    "type": "plant",
    "typeUk": "Рослина",
    "cat": "forest",
    "cr": "1/4",
    "xp": 50,
    "ac": 12,
    "hp": 20,
    "size": "Medium"
  },
  {
    "id": 15,
    "name": "Деревний страж",
    "type": "plant",
    "typeUk": "Рослина",
    "cat": "forest",
    "cr": "1",
    "xp": 200,
    "ac": 16,
    "hp": 45,
    "size": "Large"
  },
  {
    "id": 16,
    "name": "Кореневик",
    "type": "plant",
    "typeUk": "Рослина",
    "cat": "forest",
    "cr": "2",
    "xp": 450,
    "ac": 15,
    "hp": 68,
    "size": "Large"
  },
  {
    "id": 17,
    "name": "Павукар",
    "type": "aberration",
    "typeUk": "Аберація",
    "cat": "forest",
    "cr": "1",
    "xp": 200,
    "ac": 14,
    "hp": 35,
    "size": "Medium"
  },
  {
    "id": 18,
    "name": "Лісова відьма",
    "type": "fey",
    "typeUk": "Фея",
    "cat": "forest",
    "cr": "3",
    "xp": 700,
    "ac": 15,
    "hp": 65,
    "size": "Medium"
  },
  {
    "id": 19,
    "name": "Тіньовий мисливець",
    "type": "aberration",
    "typeUk": "Аберація",
    "cat": "forest",
    "cr": "2",
    "xp": 450,
    "ac": 16,
    "hp": 48,
    "size": "Medium"
  },
  {
    "id": 20,
    "name": "Старший кореневик",
    "type": "plant",
    "typeUk": "Рослина",
    "cat": "forest",
    "cr": "5",
    "xp": 1800,
    "ac": 17,
    "hp": 110,
    "size": "Huge"
  },
  {
    "id": 21,
    "name": "Печерник",
    "type": "humanoid",
    "typeUk": "Гуманоїд",
    "cat": "mountain",
    "cr": "1/8",
    "xp": 25,
    "ac": 14,
    "hp": 10,
    "size": "Small"
  },
  {
    "id": 22,
    "name": "Кам'яний рейдер",
    "type": "humanoid",
    "typeUk": "Гуманоїд",
    "cat": "mountain",
    "cr": "1/2",
    "xp": 100,
    "ac": 15,
    "hp": 22,
    "size": "Medium"
  },
  {
    "id": 23,
    "name": "Гірський велет",
    "type": "giant",
    "typeUk": "Велет",
    "cat": "mountain",
    "cr": "2",
    "xp": 450,
    "ac": 11,
    "hp": 59,
    "size": "Huge"
  },
  {
    "id": 24,
    "name": "Кіготник",
    "type": "beast",
    "typeUk": "Звір",
    "cat": "mountain",
    "cr": "1",
    "xp": 200,
    "ac": 15,
    "hp": 38,
    "size": "Medium"
  },
  {
    "id": 25,
    "name": "Кам'яний страж",
    "type": "construct",
    "typeUk": "Конструкт",
    "cat": "mountain",
    "cr": "2",
    "xp": 450,
    "ac": 17,
    "hp": 52,
    "size": "Large"
  },
  {
    "id": 26,
    "name": "Крилатий хижак",
    "type": "beast",
    "typeUk": "Звір",
    "cat": "mountain",
    "cr": "1",
    "xp": 200,
    "ac": 13,
    "hp": 32,
    "size": "Medium"
  },
  {
    "id": 27,
    "name": "Кам'яний погляд",
    "type": "monstrosity",
    "typeUk": "Монстр",
    "cat": "mountain",
    "cr": "2",
    "xp": 450,
    "ac": 15,
    "hp": 52,
    "size": "Medium"
  },
  {
    "id": 28,
    "name": "Підземний мисливець",
    "type": "monstrosity",
    "typeUk": "Монстр",
    "cat": "mountain",
    "cr": "3",
    "xp": 700,
    "ac": 17,
    "hp": 95,
    "size": "Large"
  },
  {
    "id": 29,
    "name": "Гірський гриф",
    "type": "beast",
    "typeUk": "Звір",
    "cat": "mountain",
    "cr": "5",
    "xp": 1800,
    "ac": 16,
    "hp": 95,
    "size": "Large"
  },
  {
    "id": 30,
    "name": "Древній скельник",
    "type": "elemental",
    "typeUk": "Елементаль",
    "cat": "mountain",
    "cr": "7",
    "xp": 2900,
    "ac": 18,
    "hp": 170,
    "size": "Huge"
  },
  {
    "id": 31,
    "name": "Вогняний біс",
    "type": "fiend",
    "typeUk": "Фіенд",
    "cat": "fire",
    "cr": "1/8",
    "xp": 25,
    "ac": 13,
    "hp": 10,
    "size": "Tiny"
  },
  {
    "id": 32,
    "name": "Попелястий біс",
    "type": "fiend",
    "typeUk": "Фіенд",
    "cat": "fire",
    "cr": "1/4",
    "xp": 50,
    "ac": 14,
    "hp": 16,
    "size": "Small"
  },
  {
    "id": 33,
    "name": "Магмовик",
    "type": "elemental",
    "typeUk": "Елементаль",
    "cat": "fire",
    "cr": "1/2",
    "xp": 100,
    "ac": 13,
    "hp": 22,
    "size": "Small"
  },
  {
    "id": 34,
    "name": "Вогняний елементаль",
    "type": "elemental",
    "typeUk": "Елементаль",
    "cat": "fire",
    "cr": "5",
    "xp": 1800,
    "ac": 13,
    "hp": 80,
    "size": "Large"
  },
  {
    "id": 35,
    "name": "Пекельний гончак",
    "type": "fiend",
    "typeUk": "Фіенд",
    "cat": "fire",
    "cr": "2",
    "xp": 450,
    "ac": 15,
    "hp": 45,
    "size": "Medium"
  },
  {
    "id": 36,
    "name": "Шипастий демон",
    "type": "fiend",
    "typeUk": "Фіенд",
    "cat": "fire",
    "cr": "3",
    "xp": 700,
    "ac": 15,
    "hp": 52,
    "size": "Medium"
  },
  {
    "id": 37,
    "name": "Пекельний кат",
    "type": "fiend",
    "typeUk": "Фіенд",
    "cat": "fire",
    "cr": "4",
    "xp": 1100,
    "ac": 16,
    "hp": 68,
    "size": "Medium"
  },
  {
    "id": 38,
    "name": "Вогняний змій",
    "type": "elemental",
    "typeUk": "Елементаль",
    "cat": "fire",
    "cr": "5",
    "xp": 1800,
    "ac": 16,
    "hp": 95,
    "size": "Large"
  },
  {
    "id": 39,
    "name": "Ланцюговий демон",
    "type": "fiend",
    "typeUk": "Фіенд",
    "cat": "fire",
    "cr": "5",
    "xp": 1800,
    "ac": 16,
    "hp": 85,
    "size": "Medium"
  },
  {
    "id": 40,
    "name": "Володар полум'я",
    "type": "fiend",
    "typeUk": "Фіенд",
    "cat": "fire",
    "cr": "9",
    "xp": 5000,
    "ac": 19,
    "hp": 225,
    "size": "Large"
  },
  {
    "id": 41,
    "name": "Кістяк",
    "type": "undead",
    "typeUk": "Нежить",
    "cat": "undead",
    "cr": "1/8",
    "xp": 25,
    "ac": 13,
    "hp": 13,
    "size": "Medium"
  },
  {
    "id": 42,
    "name": "Ходячий мрець",
    "type": "undead",
    "typeUk": "Нежить",
    "cat": "undead",
    "cr": "1/8",
    "xp": 25,
    "ac": 8,
    "hp": 22,
    "size": "Medium"
  },
  {
    "id": 43,
    "name": "Могильник",
    "type": "undead",
    "typeUk": "Нежить",
    "cat": "undead",
    "cr": "1/4",
    "xp": 50,
    "ac": 12,
    "hp": 22,
    "size": "Medium"
  },
  {
    "id": 44,
    "name": "Гнилий",
    "type": "undead",
    "typeUk": "Нежить",
    "cat": "undead",
    "cr": "1/2",
    "xp": 100,
    "ac": 13,
    "hp": 36,
    "size": "Medium"
  },
  {
    "id": 45,
    "name": "Тінь",
    "type": "undead",
    "typeUk": "Нежить",
    "cat": "undead",
    "cr": "1/2",
    "xp": 100,
    "ac": 12,
    "hp": 16,
    "size": "Medium"
  },
  {
    "id": 46,
    "name": "Примара",
    "type": "undead",
    "typeUk": "Нежить",
    "cat": "undead",
    "cr": "1",
    "xp": 200,
    "ac": 13,
    "hp": 30,
    "size": "Medium"
  },
  {
    "id": 47,
    "name": "Пожирач душ",
    "type": "undead",
    "typeUk": "Нежить",
    "cat": "undead",
    "cr": "2",
    "xp": 450,
    "ac": 15,
    "hp": 45,
    "size": "Medium"
  },
  {
    "id": 48,
    "name": "Безтілесний",
    "type": "undead",
    "typeUk": "Нежить",
    "cat": "undead",
    "cr": "3",
    "xp": 700,
    "ac": 16,
    "hp": 67,
    "size": "Medium"
  },
  {
    "id": 49,
    "name": "Проклятий жерць",
    "type": "undead",
    "typeUk": "Нежить",
    "cat": "undead",
    "cr": "5",
    "xp": 1800,
    "ac": 17,
    "hp": 110,
    "size": "Medium"
  },
  {
    "id": 50,
    "name": "Кровопивця",
    "type": "undead",
    "typeUk": "Нежить",
    "cat": "undead",
    "cr": "8",
    "xp": 3900,
    "ac": 16,
    "hp": 144,
    "size": "Medium"
  },
  {
    "id": 51,
    "name": "Розбійник",
    "type": "humanoid",
    "typeUk": "Гуманоїд",
    "cat": "human",
    "cr": "1/8",
    "xp": 25,
    "ac": 12,
    "hp": 11,
    "size": "Medium"
  },
  {
    "id": 52,
    "name": "Грабіжник",
    "type": "humanoid",
    "typeUk": "Гуманоїд",
    "cat": "human",
    "cr": "1/4",
    "xp": 50,
    "ac": 13,
    "hp": 16,
    "size": "Medium"
  },
  {
    "id": 53,
    "name": "Найманець",
    "type": "humanoid",
    "typeUk": "Гуманоїд",
    "cat": "human",
    "cr": "1/2",
    "xp": 100,
    "ac": 15,
    "hp": 27,
    "size": "Medium"
  },
  {
    "id": 54,
    "name": "Культист",
    "type": "humanoid",
    "typeUk": "Гуманоїд",
    "cat": "human",
    "cr": "1/8",
    "xp": 25,
    "ac": 12,
    "hp": 9,
    "size": "Medium"
  },
  {
    "id": 55,
    "name": "Фанатик",
    "type": "humanoid",
    "typeUk": "Гуманоїд",
    "cat": "human",
    "cr": "2",
    "xp": 450,
    "ac": 13,
    "hp": 33,
    "size": "Medium"
  },
  {
    "id": 56,
    "name": "Важкий боєць",
    "type": "humanoid",
    "typeUk": "Гуманоїд",
    "cat": "human",
    "cr": "1",
    "xp": 200,
    "ac": 16,
    "hp": 45,
    "size": "Medium"
  },
  {
    "id": 57,
    "name": "Ветеран",
    "type": "humanoid",
    "typeUk": "Гуманоїд",
    "cat": "human",
    "cr": "3",
    "xp": 700,
    "ac": 17,
    "hp": 58,
    "size": "Medium"
  },
  {
    "id": 58,
    "name": "Лицар",
    "type": "humanoid",
    "typeUk": "Гуманоїд",
    "cat": "human",
    "cr": "3",
    "xp": 700,
    "ac": 18,
    "hp": 52,
    "size": "Medium"
  },
  {
    "id": 59,
    "name": "Бойовий маг",
    "type": "humanoid",
    "typeUk": "Гуманоїд",
    "cat": "human",
    "cr": "5",
    "xp": 1800,
    "ac": 15,
    "hp": 60,
    "size": "Medium"
  },
  {
    "id": 60,
    "name": "Вбивця",
    "type": "humanoid",
    "typeUk": "Гуманоїд",
    "cat": "human",
    "cr": "5",
    "xp": 1800,
    "ac": 16,
    "hp": 78,
    "size": "Medium"
  }
];

export const byId = (id) => BESTIARY.find((m) => m.id === id);
